from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class StructuredProjectEvidence(BaseModel):
    """
    Structured extraction from plain-text ai_analysis_text generated by external coding AIs.
    """
    architecture: List[str] = Field(default_factory=list)
    technologies: List[str] = Field(default_factory=list)
    frameworks: List[str] = Field(default_factory=list)
    apis: List[str] = Field(default_factory=list)
    models: List[str] = Field(default_factory=list)
    databases: List[str] = Field(default_factory=list)
    deployment: List[str] = Field(default_factory=list)
    features: List[str] = Field(default_factory=list)
    technical_details: List[str] = Field(default_factory=list)
    engineering_decisions: List[str] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    verified_at: Optional[str] = None

    @field_validator(
        "architecture", "technologies", "frameworks", "apis", "models",
        "databases", "deployment", "features", "technical_details",
        "engineering_decisions", "limitations", mode="before"
    )
    def clean_str_list(cls, v):
        if isinstance(v, list):
            return [str(item).strip() for item in v if item is not None and str(item).strip()]
        if isinstance(v, str):
            return [s.strip() for s in v.split(",") if s.strip()]
        return []


class KeywordAlignment(BaseModel):
    matched_keywords: List[str] = Field(default_factory=list)
    missing_keywords: List[str] = Field(default_factory=list)
    safely_usable_keywords: List[str] = Field(default_factory=list)
    unsupported_jd_keywords: List[str] = Field(default_factory=list)


class OptimizedProject(BaseModel):
    project_id: Optional[str] = None
    project_name: str
    relevance_score: float = Field(default=1.0, ge=0.0, le=1.0)
    relevance_reasons: List[str] = Field(default_factory=list)
    matched_requirements: List[str] = Field(default_factory=list)
    technologies: List[str] = Field(default_factory=list)
    bullets: List[str] = Field(default_factory=list)
    project_url: Optional[str] = None
    github_url: Optional[str] = None
    repository_url: Optional[str] = None


from datetime import datetime, timezone

class OptimizedExperience(BaseModel):
    id: Optional[str] = None
    company: str
    role: str
    location: Optional[str] = None
    start_date: Optional[str] = ""
    end_date: Optional[str] = None
    is_current: bool = False
    bullets: List[str] = Field(default_factory=list)
    technologies: List[str] = Field(default_factory=list)


class OptimizedInternship(BaseModel):
    id: Optional[str] = None
    company: str
    role: str
    location: Optional[str] = None
    start_date: Optional[str] = ""
    end_date: Optional[str] = None
    is_current: bool = False
    bullets: List[str] = Field(default_factory=list)
    technologies: List[str] = Field(default_factory=list)


class OptimizedSkillGroup(BaseModel):
    category: str
    skills: List[str] = Field(default_factory=list)


class OptimizationMetadata(BaseModel):
    status: str = Field(default="completed", description="pending, processing, completed, or failed")
    provider: Optional[str] = None
    model: Optional[str] = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    error_message: Optional[str] = None


class OptimizedResumeData(BaseModel):
    job_id: str
    profile_snapshot_reference: Optional[str] = None
    personal_details: Dict[str, Any]
    summary: str
    education: List[Dict[str, Any]] = Field(default_factory=list)
    experience: List[OptimizedExperience] = Field(default_factory=list)
    internships: List[OptimizedInternship] = Field(default_factory=list)
    projects: List[OptimizedProject] = Field(default_factory=list)
    skills: List[OptimizedSkillGroup] = Field(default_factory=list)
    certifications: List[Dict[str, Any]] = Field(default_factory=list)
    section_order: Optional[List[str]] = None
    keyword_alignment: KeywordAlignment
    optimization_metadata: OptimizationMetadata


class OptimizationResponse(BaseModel):
    job_id: str
    company_name: str
    role_title: str
    status: str
    optimized_resume_data: Optional[OptimizedResumeData] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
